### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Movies index ###
GET http://localhost:3000/movies.json
Content-Type: application/json

### Movies show ###
GET http://localhost:3000/movies/12.json
Content-Type: application/json

### List create ###
POST http://localhost:3000/lists.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzk2ODkwNjZ9.RJCvrBa22WJjFRf23mbLHR8C7bOW8FEC3fYXTlKkH8w
Content-Type: application/json

{
  "movie_id": 4,
  "watched": false,
  "category": "not watched"
}

### List update ###
PATCH http://localhost:3000/lists/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzk2Nzk2MTh9.KWNQ12Q2qoIsxJwaGL8E0T1RGjBo2_caqbfmpeNq9Sw
Content-Type: application/json

{
  "movie_id": 4,
  "watched": false,
  "category": "Not Watched"
}