### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Phil",
  "email": "phil@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "phil@test.com",
  "password": "password"
}

### Movies index ###
GET http://localhost:3000/movies.json
Content-Type: application/json

### Movies show ###
GET http://localhost:3000/movies/86.json
Content-Type: application/json

### List create ###
POST http://localhost:3000/lists.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Mzk4NTM0MzF9.LTrqPa5BsKEy3P0J_EQWH9_97hkNz-Q-gvFU9sJ8Acc
Content-Type: application/json

{
  "watched": false,
  "category": "not watched"
}

### List update ###
PATCH http://localhost:3000/lists/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzk2Nzk2MTh9.KWNQ12Q2qoIsxJwaGL8E0T1RGjBo2_caqbfmpeNq9Sw
Content-Type: application/json

{
  "movie_id": 4,
  "watched": true,
  "category": "Loved it"
}

### Loved it add
POST http://localhost:3000/lovedits
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDIwMDI1NTZ9.B28NXlf7X9AzQ1-c9mhlCcFXHKjA6H1RBOAll4_jYyg
Content-Type: application/json

{
  "movie_id": 1
}

### hated it add
POST http://localhost:3000/hatedits
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDIxOTQ4NjN9.oHs3VhNfhmJKzR0_LdjWEffR5jyimkX6EjRrvjgLz7Q
Content-Type: application/json

{
  "movie_id": 22
}

### List Delete

DELETE http://localhost:3000/lists/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDIyNzcyOTV9.TX3WCwSydtGbggsbM9uofu_8tmPj77jfS9jSqDCE3QU
Content-Type: application/json