### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Movies index
GET http://localhost:3000/movies.json
Content-Type: application/json

### Movies show
GET http://localhost:3000/movies/12.json
Content-Type: application/json

### Watch list create
POST http://localhost:3000/watch_lists.json

