# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

### ACTION HORROR HARD CODE DATA

Movie.create!(name: "Attack Of The Killer Hog", description: "The new drug Kimanga is everywhere in the city. And the apocalypse is near. The first sign is a plush pig. But two guys are going to clear the city out and stop the apocalypse.", box_art: "https://www.themoviedb.org/t/p/w500/f9c51qg1oqxazgTAXnsZnklI5QI.jpg", sub_genre: "Action", year: 2003),
Movie.create!(name: "Demon Hunter", description: "Cosette is cursed. Demons Ghouls and Ghosts from the darkest corners of Hell are summoned to bring her to the other side. Now Cosette and Klaus her protector must face an unspeakable evil in an attempt to free her from this demonic curse.", box_art: "https://www.themoviedb.org/t/p/w500/zO98iiymllC5L995Izo5vGjeppx.jpg", sub_genre: "Action" year: 2012),
Movie.create!(name: "Jurassic Shark", description: "When an oil company unwittingly unleashes a prehistoric shark from its icy prison, the Jurassic killer maroons a group of art thieves and a group of college students on an abandoned island", box_art: "https://www.allhorror.com/public/uploads/2021/10/8yJVr0cH9w7f5pw5mjmtHMNcpr88yJVr0cH9w7f5pw5mjmtHMNcpr8-1.jpg", sub_genre: "Action" year: 2012),
Movie.create!(name: "122", description: "During a bloody night, a young man and his lover are struggling, not to get to the hospital, but to escape and survive.", box_art: "https://m.media-amazon.com/images/M/MV5BZTBiYzZhMWUtNzgzNS00ZjkzLTgxZjQtMGZmYjNhYzE1ODdlXkEyXkFqcGdeQXVyNDQ3Njc5MzM@._V1_.jpg", sub_genre: "Action", year: 2019),
Movie.create!(name: "Sky Sharks", description: "A team of Arctic geologists stumble across an abandoned laboratory in which the Nazis developed an incredible and brutal secret weapon during the final months of WW2. Deep in the ice, they accidentally awake a deadly army of flying zombie sharks ridden by genetically mutated, undead super-humans, who are unleashed into the skies, wreaking their bloodthirsty revenge on any aircraft that takes to the air.", box_art: "https://www.allhorror.com/public/uploads/2019/03/y4cxche6larlzuEsV9iwCYBubm2.jpg", sub_genre: "Action", year: 2020),
Movie.create!(name: "Originless", description: "A former drug runner battles supernatural assassins after taking a sick girl under his protection.", box_art: "https://www.allhorror.com/public/uploads/2021/10/77lI0btz8qkExY13MKXaPrf4cA677lI0btz8qkExY13MKXaPrf4cA6-1.jpg", sub_genre: "Action", year: 2020),
Movie.create!(name: "Amityville Uprising", description: "A chemical blast at a military base sets off a supernatural disaster. As Sgt. Dash tries to keep the peace at the local police station, the explosion unleashes a toxic acid rain that dissolves the flesh of anyone trapped in it. Even worse, it causes the dead to rise again and attack the living. Can Dash and fellow officer Nina Rossi figure out who is friend and foe, fend off the attacks, and defend their colleagues until the savage cataclysm subsides?", box_art: "https://www.allhorror.com/public/uploads/2021/11/RrzMH1EOUeuAogTZr1JPHsTAAg.jpg", sub_genre: "Action", year: 2022),
Movie.create!(name: "The Cursed: Dead Man’s Prey", description: "It tells the story of a girl, who pursues the truth of an incident in which the culprit of a peculiar serial murder case turns out to be a revived corpse, but who is manipulating the dead?", box_art: "https://www.allhorror.com/public/uploads/2021/07/jWe9dx74uVltztprS4SpKJRTaCY.jpg", sub_genre: "Action", year: 2021),
Movie.create!(name: "Blood Red Sky", description: "A woman with a mysterious illness is forced into action when a group of terrorists attempt to hijack a transatlantic overnight flight. In order to protect her son she will have to reveal a dark secret, and unleash the inner monster she has fought to hide.", box_art: "https://www.allhorror.com/public/uploads/2021/10/ky8Fua6PD7FyyOA7JACh3GDETli.jpg", sub_genre: "Action", year: 2021)
Movie.create!(name: "Stellanomicon: Future Fear", description: "In a distant future, an archeologist must use ancient technology in hopes of finding a way to fight back an army of alien attackers and escape the planet.", box_art: "https://www.allhorror.com/public/uploads/2021/10/xBJlIZFYumZRBL5fF8GLl4TBT2G.jpg", sub_genre: "Action", year: 2021),
Movie.create!(name: "Ebola Rex", description: "An infected T-Rex escapes from a Science Lab in downtown Los Angeles, destroying everything in it's path.", box_art: "https://www.allhorror.com/public/uploads/2021/03/yXKNAuL3SRog5hB3l3ykVOZqhhC.jpg", sub_genre: "Action", year: 2021),

### ALIENS HORROR HARD CODE DATA

Movie.create!(name: "Village Of The Damned", description: "In a small English village everyone suddenly falls unconscious. When they awake every woman of child bearing age is pregnant. The resulting children have the same strange blond hair, eyes and a strong connection to each other.", box_art: "https://www.allhorror.com/public/uploads/2021/10/qcpXud1UjQzlSe9A062w8Wqgira.jpg", sub_genre: "Alien", year: 1960),
Movie.create!(name: "The Crawling Eye", description: "Alien creatures invade a remote mountain resort in Switzerland.", box_art: "https://www.allhorror.com/public/uploads/2021/10/onncV1X9RRk7vs9vJ0mpCeFIrzQ.jpg", sub_genre: "Alien", year: 1958),
Movie.create!(name: "Alien", description: "During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.", box_art: "https://www.allhorror.com/public/uploads/2021/10/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg", sub_genre: "Alien", year: 1979),
Movie.create!(name: "Phantasm", description: "A young boy and his friends face off against a mysterious grave robber known only as the Tall Man, who keeps a mysterious arsenal of terrible weapons with him.", box_art: "https://www.allhorror.com/public/uploads/2021/10/eR0uJ0Wje1lYJ4aHEpkcjgIM8d7.jpg", sub_genre: "Alien", year: 1979),
Movie.create!(name: "The Thing", description: "Scientists in the Antarctic are confronted by a shape-shifting alien that assumes the appearance of the people it kills.", box_art: "https://www.allhorror.com/public/uploads/2021/10/tzGY49kseSE9QAKk47uuDGwnSCu.jpg", sub_genre: "Alien", year: 1982),
Movie.create!(name: "They Live", description: "Nada, a down-on-his-luck construction worker, discovers a pair of special sunglasses. Wearing them, he is able to see the world as it really is: people being bombarded by media and government with messages like "Stay Asleep", "No Imagination", "Submit to Authority". Even scarier is that he is able to see that some usually normal-looking people are in fact ugly aliens in charge of the massive campaign to keep humans subdued.", box_art: "https://www.allhorror.com/public/uploads/2021/10/ngnybFTuopfbfmmEeX9jjBQQmF6.jpg", sub_genre: "Alien", year: 1988),
Movie.create!(name: "Dreamcatcher", description: "Four boyhood pals perform a heroic act and are changed by the powers they gain in return. Years later, on a hunting trip in the Maine woods, they're overtaken by a vicious blizzard that harbors an ominous presence. Challenged to stop an alien force, the friends must first prevent the slaughter of innocent civilians by a military vigilante ... and then overcome a threat to the bond that unites the four of them.", box_art: "https://www.allhorror.com/public/uploads/2021/10/vEA305YK7QCjK02NP5OFqYsDEVQ.jpg", sub_genre: "Alien", year: 2003),
Movie.create!(name: "Rakka", description: "A tale of a dystopian future where an unknown alien group have colonised the earth and humans struggle to fight back.", box_art: "https://www.allhorror.com/public/uploads/2021/10/4wVeP9BHsQul7CRgdrfiUt1Rds14wVeP9BHsQul7CRgdrfiUt1Rds1-1.jpg", sub_genre: "Alien", year: 2017),
Movie.create!(name: "Psycho Goreman", description: "Siblings Mimi and Luke unwittingly resurrect an ancient alien overlord. Using a magical amulet, they force the monster to obey their childish whims, and accidentally attract a rogues’ gallery of intergalactic assassins to small-town suburbia.", box_art: "https://www.allhorror.com/public/uploads/2021/10/foQnDv051kQ7satMQkbkPsUxzkDfoQnDv051kQ7satMQkbkPsUxzkD-1.jpg", sub_genre: "Alien", year: 2021),
Movie.create!(name: "Invaders From Mars", description: "In the early hours of the night, young David Maclean sees a flying saucer land and disappear into the sand dunes just beyond his house. Slowly, all of the adults, including his once loving parents, begin to act strangely.", box_art: "https://www.allhorror.com/public/uploads/2021/10/pVR2c0bigL5w1K29H99svqHj2YHpVR2c0bigL5w1K29H99svqHj2YH-1.jpg", sub_genre: "Alien", year: 1953),

### ANTHOLOGY HARD CODE DATA

Movie.create!(name: "Dr. Terror's House Of Horrors", description: "A man of mystery known only as Doctor Terror recounts seven stories from his casebook of personal encounters with evil and the supernatural.", box_art: "https://www.allhorror.com/public/uploads/2018/10/iNJSXyRPbke0daGrXU8FGZLbpbdiNJSXyRPbke0daGrXU8FGZLbpbd-1.jpg", sub_genre: "Anthology", year: 1943),
Movie.create!(name: "Trilogy Of Terror", description: "Three bizarre horror stories ending with the story of an African doll out for blood.", box_art: "https://www.allhorror.com/public/uploads/2021/10/2t2TJz5cIVQuzQsQWFZFNYfuFnm.jpg", sub_genre: "Anthology", year: 1975),
Movie.create!(name: "Creepshow", description: "Inspired by the E.C. comics of the 1950s, George A. Romero and Stephen King bring five tales of terror to the screen.", box_art: "https://www.allhorror.com/public/uploads/2021/10/4SoyTCEpsgLjX6yAyMsx3AsAyRQ.jpg", sub_genre: "Anthology", year: 1982),
Movie.create!(name: "Cradle Of Fear", description: "A gruesome homage to the cult Amicus anthology Asylum, Cradle of Fear unfolds four screamplays all linked by the unspeakable need of an incarcerated child killer to wreak vengeance on those responsible for his imprisonment.", box_art: "https://www.allhorror.com/public/uploads/2021/10/qYNYAFCBd83fOAWIIiL4nG6L2zq.jpg", sub_genre: "Anthology", year: 2001),
Movie.create!(name: "V/H/S", description: "When a group of misfits is hired by an unknown third party to burglarize a desolate house and acquire a rare VHS tape, they discover more found footage than they bargained for.", box_art: "https://www.allhorror.com/public/uploads/2018/03/yo49x6Jhr1ecCjy1ByFqwAbtARJ.jpg", sub_genre: "Anthology", year: 2012),
Movie.create!(name: "All Hallows' Eve", description: "While watching two children on Halloween night, a babysitter finds an old VHS tape in the kids' trick or treat bag. The tape features three tales of terror, all linked together by a murderous clown. As the night goes on strange things begin to occur in the house. It isn't long before the babysitter learns the horrifying truth... the maniacal clown is slowly working his way into her reality.", box_art: "https://www.allhorror.com/public/uploads/2018/03/uh2DbCCj83krRPl3X2wYMQQLasZuh2DbCCj83krRPl3X2wYMQQLasZ-1.jpg", sub_genre: "Anthology", year: 2013),
Movie.create!(name: "The ABCs Of Death", description: "An ambitious anthology film featuring segments directed by over two dozen of the world's leading talents in contemporary genre film. Inspired by children's educational ABC books, the motion picture is comprised of 26 individual chapters, each helmed by a different director assigned a letter of the alphabet", box_art: "https://www.allhorror.com/public/uploads/2018/03/9rAaRHk7GkYCxjOlBnJLC0kXrSy.jpg",  sub_genre: "Anthology", year: 2013),
Movie.create!(name: "Killroy Was Here", description: "A horror anthology centred around the phenomenon of the "Kilroy Was Here" graffiti.",box_art: "https://www.allhorror.com/public/uploads/2020/08/kZNop4kIfPmghbPrvLNPTPyz6tw.jpg",sub_genre: "Anthology",year: 2020),
Movie.create!(name: "The Haunted Hotel", description: "A compendium of eight ghost stories, all set within an abandoned hotel in Suffolk.", box_art: "https://www.allhorror.com/public/uploads/2021/10/rtQnew9MbwUb1hmF2E65j5LJdkLrtQnew9MbwUb1hmF2E65j5LJdkL-1.jpg", sub_genre: "Anthology", year: 2021),
Movie.create!(name: "Tales From The Hood", description: "A strange funeral director tells four strange tales of horror with an African American focus to three drug dealers he traps in his place of business.", box_art: "https://www.allhorror.com/public/uploads/2021/10/rmlDLtt03igCdlW7UOF2AXCsy4d.jpg",
sub_genre: "Anthology", year: 1995),

### BLACK HORROR HARD CODE DATA

Movie.create!(name: "Blacula", description: "An 18th century African prince is turned into a vampire while visiting Transylvania. Two centuries later, he rises from his coffin attacking various residents of Los Angeles and meets Tina, a woman who he believes is the reincarnation of his deceased wife.",box_art: "https://www.allhorror.com/public/uploads/2021/10/yLqtFeZfRPoUUzzro3ogCdobB6q.jpg", sub_genre: "Black Horror", year: 1972),
Movie.create!(name: "Scream Blacula Scream", description: "After a dying Voodoo queen chooses an adopted apprentice as her successor, her true heir is outraged. Seeking revenge, he buys the bones of Blacula the vampire off of a dealer, and uses voodoo to bring the vampire back to do his bidding.", box_art: "https://www.allhorror.com/public/uploads/2021/10/fNj2dm4YTboK73uNcctP9ABzl6i.jpg", sub_genre: "Black Horror", year: 1973),
Movie.create!(name: "Bones", description: "Over 20 years after his death by a gunshot, Jimmy Bones comes back as a ghost to wreak revenge on those who killed him and to clean up his neighborhood.", box_art: "https://www.allhorror.com/public/uploads/2021/10/7UOHEPTQMaiwaI14CGxd5yFAPMZ.jpg", sub_genre: "Black", year: 2001),
Movie.create!(name: "Shadow: Dead Riot", description: "Evil voodoo-practicing serial killer Shadow gets executed for murdering pregnant women. Twenty years later the prison Shadow was put to death at has been turned into an experimental women's penitentiary. Tough and fiercely autonomous new inmate Solitaire has some kind of link with Shadow. When Shadow and his lethal shambling zombie minions are resurrected, it's up to Solitaire to stop them.", box_art: "https://www.allhorror.com/public/uploads/2021/10/labFmu8KL7DGIOp9w5n5PNQALtl.jpg", sub_genre: "Black Horror", year: 2006),
Movie.create!(name: "Nailed", description: "A pair of crooks on the run from the law gets more than they bargained for when they break into a seemingly abandoned house looking for a place to hole up and find that it's controlled by an evil spirit that will do anything to protect its sole, sickly resident. Suddenly, jail's not looking so bad.", box_art: "https://www.allhorror.com/public/uploads/2018/03/rb8pbhDwZU1EFmS3SdrNHlllBR4-238x347.jpg", sub_genre: "Black", year: 2006),
Movie.create!(name: "Killjoy", description: "Deep in an inner city hell, a ghastly figure is killing off the bad guys. A vigilante, or a demon? For the beautiful high school student, Jada, that's the question that will bring her face to face with the killer clown Killjoy.", box_art: "https://www.allhorror.com/public/uploads/2018/03/7mqFe0lNXRuzTqLO2pxoj9H6stU-230x357.jpg", sub_genre: "Black Horror", year: 2000),
Movie.create!(name: "Vampire In Brooklyn", description: "Maximillian, the lone survivor of a race of vampires, comes to Brooklyn in search of a way to live past the next full moon. His ticket to survival is Rita, a NYPD detective who doesn't know she's half vampire -- and Maximillian will do whatever's necessary to put her under his spell.", box_art: "https://www.allhorror.com/public/uploads/2021/10/i8ZD5LsBjwF45MsZ1nCClpvaOcn.jpg", sub_genre: "Black Horror", year: 1995),
Movie.create!(name: "Horror Noire", description: "Presents together six horror stories from Black directors and screenwriters in a single film:", box_art: "https://www.allhorror.com/public/uploads/2021/10/Horror%20Noire%202021%20-%201.jpg", sub_genre: "Black Horror", year: 2021),
Movie.create!(name: "Crack House Of The Dead", description: "On the dawn of a zombie outbreak an undercover drug deal goes wrong forcing the cop, the dealer, and others urban misfits to take refuge in the last safe place in the city - a Crack House", box_art: "https://www.allhorror.com/public/uploads/2021/06/wmgDd9UFoxHtgMQPn3lPWN2Gwu9.jpg", sub_genre: "Black Horror", year: 2021),
Movie.create!(name: "Death Ranch", description: "In 1970s America, three African-American siblings on the run from the police take refuge at an abandoned Tennessee Ranch, unaware their hideout is on the hunting grounds of a cannibalistic Ku Klux Klan cult. Trapped and tortured, the three must fight tooth and nail to escape alive and take down the bloodthirsty Klan.", box_art: "https://www.allhorror.com/public/uploads/2021/10/52H7mdfL4r2Q2aAaIyJJ6l4JhI.jpg", sub_genre: "Black Horror", year: 2020),

### CABIN IN THE WOODS HARD CODE DATA

Movie.create!(name: "The Evil Dead", description: "When a group of college students finds a mysterious book and recording in the old wilderness cabin they've rented for the weekend, they unwittingly unleash a demonic force from the surrounding forest.", box_art: "https://www.allhorror.com/public/uploads/2021/10/uYxQ6xhP3WjqPZtxyAOnZQWnZqn.jpg", sub_genre: "Cabin in the woods", year: 1981),
Movie.create!(name: "Misery", description: "Novelist Paul Sheldon crashes his car on a snowy Colorado road. He is found by Annie Wilkes, the "number one fan" of Paul's heroine Misery Chastaine. Annie is also somewhat unstable, and Paul finds himself crippled, drugged and at her mercy.", box_art: "https://www.allhorror.com/public/uploads/2018/05/s0Ot5zUmVF1jSN9WpBHRafvUPld.jpg", sub_genre: "Cabin in the woods", year: 1990),
Movie.create!(name: "Cabin Fever", description: "A group of five college graduates rent a cabin in the woods and begin to fall victim to a horrifying flesh-eating virus, which attracts the unwanted attention of the homicidal locals.", box_art: "https://www.allhorror.com/public/uploads/2021/10/lsGAVZ4gc3ctgNDdVbU9KQb1oxV.jpg", sub_genre: "Cabin in the woods", year: 2003),
Movie.create!(name: "The Cabin In The Woods", description: "Five college friends spend the weekend at a remote cabin in the woods, where they get more than they bargained for. Together, they must discover the truth behind the cabin in the woods.", box_art: "https://www.allhorror.com/public/uploads/2018/03/utfJuX6DfR28Mv2FMfnPFAYOmTU.jpg", sub_genre: "Cabin in the woods", year: 2012),
Movie.create!(name: "Antichrist", description: "A grieving couple retreats to their cabin 'Eden' in the woods, hoping to repair their broken hearts and troubled marriage. But nature takes its course and things go from bad to worse.", box_art: "https://www.allhorror.com/public/uploads/2018/03/lY4Y9buUIZY17vpvL5dsBpbORo0.jpg", sub_genre: "Cabin in the woods", year: 2009),
Movie.create!(name: "Ghost Of Camp Blood", description: "For years, the infamous Blackwood Forest was terrorized by the Camp Blood Killer. Now, the killer is back as a vengeful spirit seeking revenge from beyond the grave.", box_art: "https://www.allhorror.com/public/uploads/2021/10/eXPeyhotpz2zqJM7DossNuXYsYbeXPeyhotpz2zqJM7DossNuXYsYb-1.jpg", sub_genre: "Cabin in the woods", year: 2018),
Movie.create!(name: "Toys Of Terror", description: "A big family moves into a dusty old house in the snowy woods of Washington with hopes of it being a nice holiday escape. But the kids soon discover a stash of old toys that just so happen to belong to a creepy ghost boy. As stranger and stranger things start to happen, some of the kids begin to sense that something in the house is not quite right…", box_art: "https://www.allhorror.com/public/uploads/2021/10/c6hmAgPVXxZHwMHfS9z3W2n9Gz9c6hmAgPVXxZHwMHfS9z3W2n9Gz9-1.jpg", sub_genre: "Cabin in the woods", year: 2020),
Movie.create!(name: "Gaia", description: "On a surveillance mission in a primordial forest, a park ranger encounters two survivalists following a post-apocalyptic lifestyle. The boy and his philosophical father seem to have their own religion, and a mysterious relationship to nature. There are many suspicious aspects to their existence, but when the cabin is attacked by strange, post-human beings one night, she learns that there is a greater threat in this emergent wilderness. Gaia is an ecological horror fantasy which engages the burning issues of our time.", box_art: "https://www.allhorror.com/public/uploads/2021/10/v8cwfPwjHDWf5s5MxvLvcfnxPLLv8cwfPwjHDWf5s5MxvLvcfnxPLL-1.jpg", sub_genre: "Cabin in the woods", year: 2021),
Movie.create!(name: "The House That Eats Flesh", description: "There is a house that has been passed down from generation to generation, but it isn't just any ordinary house. This house is built on the Gates of Hell. This Thanksgiving a group of friends desperate to have a nice holiday together, will discover the truth of what goes on inside. It's the age old saying "what happens inside the house, stays inside the house". The doors are locked, the windows are barred, and something sinister is breaking through the floor.", box_art: "https://www.allhorror.com/public/uploads/2021/11/qn0wv5Jr3W8CX9f5h4o7g6B8IKU.jpg", sub_genre: "Cabin in the woods", year: 2022),
Movie.create!(name: "Boomika", description: "Paranormal activity at a lush, abandoned property alarm a group eager to redevelop the site, but the eerie events may not be as unearthly as they think.", box_art: "https://www.allhorror.com/public/uploads/2021/11/nOFBVKFtXfWUx3ZMPAEp05QD5eD.jpg", sub_genre: "Cabin in the woods", year: 2021),

### CLASSIC HARD CODE DATA

Movie.create!(name: "The Cabinet Of Dr. Caligari", description: "The Cabinet of Dr. Caligari is eerie and expressionistic, silent and surreal. It has become not only a classic of German Expressionist cinema, but a landmark in film history, with creative scenery and an unusual ending", box_art: "https://www.allhorror.com/public/uploads/2021/10/myK9DeIsXWGKgUTZyGXg2IfFk0W.jpg", sub_genre: "Classic Horror", year: 1920),
Movie.create!(name: "Nosferatu", description: "Vampire Count Orlok is interested in a new residence and in real estate agent Hutter's young wife. Silent horror classic based on the Bram Stoker novel "Dracula".", box_art: "https://www.allhorror.com/public/uploads/2021/10/zx24O7VAs6NbJhiIrUhWysAiHS0.jpg", sub_genre: "Classic Horror", year: 1922),
Movie.create!(name: "The Man Who Laughs", description: "Gwynplaine, son of Lord Clancharlie, has a permanent smile carved on his face by the King, in revenge for Gwynplaine's father's treachery. Gwynplaine is adopted by a travelling showman and becomes a popular idol. He falls in love with the blind Dea. The king dies, and his evil jester tries to destroy or corrupt Gwynplaine.", box_art: "https://www.allhorror.com/public/uploads/2021/10/5wdVqamH2NfW36OH6BvLCwqLnbA.jpg", sub_genre: "Classic Horror", year: 1928),
Movie.create!(name: "Frankenstein", description: "Henry Frankenstein is a doctor who is trying to discover a way to make the dead walk. He succeeds and creates a monster that has to deal with living again.", box_art: "https://www.allhorror.com/public/uploads/2021/10/jFpc9w3RmYeaOXMEfrtgshwVf4u.jpg", sub_genre: "Classic Horror", year: 1931),
Movie.create!(name: "Dracula", description: "The legend of vampire Count Dracula begins here with this original 1931 Dracula film from Bela Lugosi.", box_art: "https://www.allhorror.com/public/uploads/2021/10/ueVSPt7vAba0XScHWTDWS5tNxYX.jpg", sub_genre: "Classic Horror", year: 1931),
Movie.create!(name: "Freaks", description: "A circus' beautiful trapeze artist agrees to marry the leader of side-show performers, but his deformed friends discover she is only marrying him for his inheritance.", box_art: "https://www.allhorror.com/public/uploads/2021/10/j2dwljljOrLTcnwfKeUBBeNB8t7.jpg", sub_genre: "Classic Horror", year: 1932),
Movie.create!(name: "The Masque Of The Red Death", description: "Satan-worshiper Prince Prospero invites the local nobility to his castle for protection against an oncoming plague, the Red Death. He orders his guests to attend a masked ball and, amidst an atmosphere of debauchery and depravity, notices the entry of a hooded stranger dressed all in red. Believing the figure to be his master, Satan, Prospero is horrified at the revelation of his true identity.", box_art: "https://www.allhorror.com/public/uploads/2021/10/pPHVp6XVaSK5Hkbmf7HYdrts9kJ.jpg", sub_genre: "Classic Horror", year: 1964),
Movie.create!(name: "House On Haunted Hill", description: "Frederick Loren has invited five strangers to a party of a lifetime. He is offering each of them $10,000 if they can stay the night in a house. But the house is no ordinary house. This house has a reputation for murder. Frederick offers them each a gun for protection. They all arrived in a hearse and will either leave in it $10,000 richer or leave in it dead!", box_art: "https://www.allhorror.com/public/uploads/2021/10/g5kdFt3piV3w1pG65W9sSToJ7HB.jpg", sub_genre: "Classic Horror", year: 1959),
Movie.create!(name: "The Black Sleep", description: "In 19th century England, a noted brain surgeon rescues a former student from being hanged on a false conviction for murder, and spirits him away to an ancient, repurposed abbey far in the countryside. There, he connives his pupil into assisting him in mapping the functions of the various parts of the human brain, using living subjects who are under a terrible animation-suspending drug called "black sleep".", box_art: "https://www.allhorror.com/public/uploads/2021/10/aIGG1C5t8qS4S0wfaVOdZRzYGwY.jpg", sub_genre: "Classic Horror", year: 1956),
Movie.create!(name: "House Of Wax", description: "A horribly disfigured sculptor opens up the House of Wax in New York, using the wax-covered bodies of his victims as his displays.", box_art: "https://www.allhorror.com/public/uploads/2021/10/mzJiyWeX8QsOOYCa0gESTn91rfm.jpg", sub_genre: "Classic Horror", year: 1953),

### COMEDY HARD CODE DATA

Movie.create!(name: "Yoga Hoser", description: "Two teenage yoga enthusiasts team up with a legendary man-hunter to battle with an ancient evil presence that is threatening their major party plans.", box_art: "https://www.allhorror.com/public/uploads/2018/04/t9K1uUCJsbrFGKYivSH1JBPfvyc.jpg", sub_genre: "Comedy Horror", year: 2016),
Movie.create!(name: "Tusk", description: "When his best friend and podcast co-host goes missing in the backwoods of Canada, a young guy joins forces with his friend's girlfriend to search for him.", box_art: "https://www.allhorror.com/public/uploads/2018/03/ntxILPesM4IRumijc1DRJQTks9t.jpg", sub_genre: "Comedy Horror", year: 2014),
Movie.create!(name: "Tucker And Dale Vs Evil", description: "Two hillbillies are suspected of being killers by a group of paranoid college kids camping near the duo's West Virginian cabin. As the body count climbs, so does the fear and confusion as the college kids try to seek revenge against the pair.", box_art: "https://www.allhorror.com/public/uploads/2018/03/lNaivZXcad1bXDoptUzV3PQ2Ms0.jpg", sub_genre: "Comedy Horror", year: 2010),
Movie.create!(name: "Dead Snow", description: "Eight medical students on a ski trip to Norway discover that Hitler's horrors live on when they come face to face with a battalion of zombie Nazi soldiers intent on devouring anyone unfortunate enough to wander into the remote mountains where they were once sent to die.", box_art: "https://www.allhorror.com/public/uploads/2018/03/nDWI0SP3go01b5STPcAwQSK3eCc.jpg", sub_genre: "Comedy Horror", year: 2009),
Movie.create!(name: "Shaun Of The Dead", description: "Shaun lives a supremely uneventful life, which revolves around his girlfriend, his mother, and, above all, his local pub. This gentle routine is threatened when the dead return to life and make strenuous attempts to snack on ordinary Londoners.", box_art: "https://www.allhorror.com/public/uploads/2021/10/dgXPhzNJH8HFTBjXPB177yNx6RI.jpg", sub_genre: "Comedy Horror", year: 2004),
Movie.create!(name: "Willy's Wonderland", description: "A janitor is forced to spend the night in a twisted amusement park where he is pulled into a living nightmare. As the threatening animatronic characters come to life, the janitor has to fight his way from one monster to another to survive until morning and get out of the park.", box_art: "https://www.allhorror.com/public/uploads/2021/10/keEnkeAvifw8NSEC4f6WsqeLJgF.jpg", sub_genre: "Comedy Horror", year: 2021),
Movie.create!(name: "The Rocky Horror Picture Show", description: "Sweethearts Brad and Janet, stuck with a flat tire during a storm, discover the eerie mansion of Dr. Frank-N-Furter, a transvestite scientist. As their innocence is lost, Brad and Janet meet a houseful of wild characters, including a rocking biker and a creepy butler. Through elaborate dances and rock songs, Frank-N-Furter unveils his latest creation: a muscular man named 'Rocky'.", box_art: "https://www.allhorror.com/public/uploads/2021/10/3pyE6ZqDbuJi7zrNzzQzcKTWdmN.jpg", sub_genre: "Comedy Horror", year: 1975),
Movie.create!(name: "Young Frankenstein", description: "A young neurosurgeon inherits the castle of his grandfather, the famous Dr. Victor von Frankenstein. In the castle he finds a funny hunchback, a pretty lab assistant and the elderly housekeeper. Young Frankenstein believes that the work of his grandfather was delusional, but when he discovers the book where the mad doctor described his reanimation experiment, he suddenly changes his mind.", box_art: "https://www.allhorror.com/public/uploads/2018/06/tQJAWbIjvvqVKLLbIZHtwGw2HTf.jpg", sub_genre: "Comdey Horror", year: 1974),
Movie.create!(name: "Fear", description: "Horror junkie Joe Foster gets to live out his ultimate scary movie fantasy courtesy of Fear Inc., a company that specializes in giving you the fright of your life. But as lines blur between what is and is not part of the game, Joe's dream come true begins to look more like a nightmare.", box_art: "https://www.allhorror.com/public/uploads/2018/03/mbsX8ZynHg6FoD1Pt6j2jCRAZBu.jpg", sub_genre: "Comdey Horror", year: 2016),
Movie.create!(name: "Deathgasm", description: "Two teenage boys unwittingly summon an ancient evil entity known as The Blind One by delving into black magic while trying to escape their mundane lives.", box_art: "https://www.allhorror.com/public/uploads/2018/03/cwy9sGEOAuzpZXzXBVln1PZ4vxn.jpg", sub_genre: "Comedy Horror", year: 2015),

### CREATURES HARD CODE DATA

Movie.create!(name: "The Mist", description: "After a violent storm, a dense cloud of mist envelops a small Maine town, trapping artist David Drayton and his five-year-old son in a local grocery store with other people. They soon discover that the mist conceals deadly horrors that threaten their lives, and worse, their sanity.", box_art: "https://www.allhorror.com/public/uploads/2018/03/uYVheUBf8ITaocUP4Og9GXxOMIH.jpg", sub_genre: "Creature Horror", year: 2007),
Movie.create!(name: "The Fly", description: "When Seth Brundle makes a huge scientific and technological breakthrough in teleportation, he decides to test it on himself. Unbeknownst to him, a common housefly manages to get inside the device and the two become one.", box_art: "https://www.allhorror.com/public/uploads/2021/10/erQDGPbEatMEWFrB6KqNTNXtAtn.jpg", sub_genre: "Creature Horror", year: 1986),
Movie.create!(name: "C.H.U.D.", description: "A rash of bizarre murders in New York City seems to point to a group of grotesquely deformed vagrants living in the sewers. A courageous policeman, a photo journalist and his girlfriend, and a nutty bum, who seems to know a lot about the creatures, band together to try and determine what the creatures are and how to stop them.", box_art: "https://www.allhorror.com/public/uploads/2021/10/8BVw5RIDBTZwdMAR1VKpAkwrMjj.jpg", sub_genre: "Creature Horror", year: 1984),
Movie.create!(name: "Superbeast", description: "A doctor finds a jungle laboratory, complete with mad scientist and genetic engineering experiments", box_art: "https://www.allhorror.com/public/uploads/2021/10/mrDPcoQy9S3CitwkHc30vLCLGgD.jpg", sub_genre: "Creature Horror", year: 1972),
Movie.create!(name: "The Golem", description: "In this version of the golem legend, the golem, a clay statue brought to life by Rabbi Loew in 16th century Prague to save the Jews from the ongoing brutal persecution by the city's rulers, is found in the rubble of an old synagogue in the 20th century. Brought to life by an antique dealer, the golem is used as a menial servant. Eventually falling in love with the dealer's wife, it goes on a murderous rampage when its love for her goes unanswered. This mostly lost film (please check your attic) is often confused with director Paul Wegener second and readily available interpretation of the legend; Der Golem, wie er in die Welt kam (1920).", box_art: "https://www.allhorror.com/public/uploads/2019/01/zW1xgMLIqcCmF6S2ic9oy3ncWrE.jpg", sub_genre: "Creature Horror", year: 1915),
Movie.create!(name: "The Blob", description: "Remake of the 1958 horror sci-fi about a deadly blob which is the spawn of a secret government germ warfare project which consumes everyone in its path. Teenagers try in vain to warn the townsfolk, who refuse to take them seriously, while government agents try to cover up the evidence and confine the creature.", box_art: "https://www.allhorror.com/public/uploads/2021/10/otYUfKbmgv20ZPMaynp2AHRjlYd.jpg", sub_genre: "Creature Horror", year: 1988),
Movie.create!(name: "Pumpkinhead", description: "A man conjures up a gigantic vengeance demon called Pumpkinhead to destroy the teenagers who accidentally killed his son.", box_art: "https://www.allhorror.com/public/uploads/2021/10/jlYXLlsziG7IiYSjhaNwBMCIgxx.jpg", sub_genre: "Creature Horror", year: 1988),
Movie.create!(name: "Predator", description: "Dutch and his group of commandos are hired by the CIA to rescue downed airmen from guerillas in a Central American jungle. The mission goes well but as they return they find that something is hunting them. Nearly invisible, it blends in with the forest, taking trophies from the bodies of its victims as it goes along. Occasionally seeing through its eyes, the audience sees it is an intelligent alien hunter, hunting them for sport, killing them off one at a time.", box_art: "https://www.allhorror.com/public/uploads/2018/05/p6fhq04t75yCfE0kSTNZGQvWuQ1.jpg", sub_genre: "Creature Horror", year: 1987),
Movie.create!(name: "Ghoulies", description: "A young man and his girlfriend move into the man's old mansion home, where he becomes possessed by a need to control ancient demons.", box_art: "https://www.allhorror.com/public/uploads/2021/10/ks88iJM3ykJmP0qK5IAHURpDfNi.jpg", sub_genre: "Creature Horror", year: 1984),
Movie.create!(name: "Cujo", description: "A friendly St. Bernard named "Cujo" contracts rabies and conducts a reign of terror on a small American town.", box_art: "https://www.allhorror.com/public/uploads/2021/10/uNBt2YxrQdyOjnm2rDQ5QiCmQ0K.jpg", sub_genre: "Creature Horror", year: 1983),

### DEAMONS HARD CODE DATA

Movie.create!(name: "Rosemary's Baby", description: "A young couple moves into an infamous New York apartment building to start a family. Things become frightening as Rosemary begins to suspect her unborn baby isn't safe around their strange neighbors", box_art: "https://www.allhorror.com/public/uploads/2018/04/kqA1pt9ovovArgJZi2Lu4Unf6HekqA1pt9ovovArgJZi2Lu4Unf6He-1.jpg", sub_genre: "Demon Horror", year: 1968),
Movie.create!(name: "The Exorcist", description: "12-year-old Regan MacNeil begins to adapt an explicit new personality as strange events befall the local area of Georgetown. Her mother becomes torn between science and superstition in a desperate bid to save her daughter, and ultimately turns to her last hope: Father Damien Karras, a troubled priest who is struggling with his own faith.", box_art: "https://www.allhorror.com/public/uploads/2021/10/4ucLGcXVVSVnsfkGtbLY4XAius8.jpg", sub_genre: "Demon Horror", year: 1973),
Movie.create!(name: "Hellraiser", description: "Larry and his wife, Julia move into an old house and discover a hideous creature - the man's half-brother, who is also the woman's former lover - hiding upstairs. Having lost his earthly body to a trio of S&M demons, the Cenobites, Frank, is brought back into existence by a drop of blood on the floor. He soon forces his former mistress to bring him his necessary human sacrifices to complete his body... but the Cenobites won't be happy about this.", box_art: "https://www.allhorror.com/public/uploads/2021/10/3Z0oPHyLnk3Vx6ZMC1MiVwIrKhO.jpg", sub_genre: "Demon Horror", year: 1987),
Movie.create!(name: "Jeepers Creepers", description: "A college-age brother and sister get more than they bargained for on their road trip home from spring break. When the bickering siblings witness a creepy truck driver tossing body bags into a sewer near an abandoned church, they investigate. Bad move! Opening a Pandora's Box of unspeakable evil, the pair must flee for their lives -- with a monstrous "shape" in hot pursuit.", box_art: "https://www.allhorror.com/public/uploads/2021/10/g410Y1U1ELbmJG14Zru3UAimm1G.jpg", sub_genre: "Demon Horror", year: 2001),
Movie.create!(name: "Wishmaster", description: "The Djinn having been released from his ancient prison seeks to capture the soul of the woman who discovered him, thereby opening a portal and freeing his fellow Djinn to take over the earth.", box_art: "https://www.allhorror.com/public/uploads/2021/10/t7rep7SCqiy4COUsq2cOcdQwzU0.jpg", sub_genre: "Demon Horror", year: 1997),
Movie.create!(name: "Spawn", description: "After being murdered by corrupt colleagues in a covert government agency, Al Simmons (Michael Jai White) makes a pact with the devil to be resurrected to see his beloved wife Wanda (Theresa Randle). In exchange for his return to Earth, Simmons agrees to lead Hell's Army in the destruction of mankind.", box_art: "https://www.allhorror.com/public/uploads/2018/05/tfvH5YKXtMiBgkj0FNozQj4TQyp.jpg", sub_genre: "Demon Horror", year: 1997),
Movie.create!(name: "Puppet Master", description: "Toulon, a puppet maker, discovers an ancient Egyptian potion and uses it to bring his creations to life. His puppets become murderous little demons and escape. Distraught, the master takes his life. Years later, psychics tune into the existence of the monstrous marionettes and set off to stop them.", box_art: "https://www.allhorror.com/public/uploads/2021/10/tIVOIxMzSZ4Jw13ip2rzeUu1qvD.jpg", sub_genre: "Demon Horror", year: 1989),
Movie.create!(name: "Baba Yaga: Terror Of The Dark Forest", description: "The young family who moved to a new apartment on the outskirts of the city. The nanny hired by them for the newborn daughter quickly gained confidence. However, the older boy, Egor, talks about the frightening behavior of a woman, but his parents do not believe him. The surveillance cameras installed by the father for comfort only confirm everything is in order. Then one day, Egor, returning home, finds no trace of either the nanny or the little sister, and the parents are in a strange trance and do not even remember that they had a daughter. Then Egor, together with his friends, goes in search, during which it turns out that the nanny is an ancient Slavic demon, popularly known as Baba Yaga.", box_art: "https://www.allhorror.com/public/uploads/2019/12/nafHARcES2Mz0Z0qQEUcUMGQaB4nafHARcES2Mz0Z0qQEUcUMGQaB4-1.jpg", sub_genre: "Demon Horror", year: 2020),
Movie.create!(name: "Demon House", description: "As mass hysteria breaks-out over an alleged demonic possession in an Indiana home, referred to as a “Portal to Hell,” Ghost Adventures host and paranormal investigator Zak Bagans buys the house, sight unseen, over the phone. He and his crew then become the next victims of the most documented case of demonic possession in US history… the “house of 200 demons.", box_art: "https://www.allhorror.com/public/uploads/2018/05/80gFuW9wIeKEaswSspSGjSEOcDE.jpg", sub_genre: "Demon Horror", year: 2018),
Movie.create!(name: "Another Evil", description: "After encountering a ghost in his family's vacation home, Dan and his wife Mary hire an "industrial-grade exorcist" named Os to get rid of the beings.", box_art: "https://www.allhorror.com/public/uploads/2018/05/fC73oC0xwssWc7ty6dspPvgqfyz.jpg", sub_genre: "Demon Horror", year: 2017),

### DOCUMENTARY HARD CODE DATA

Movie.create!(name: "Faces Of Death", description: "A collection of death scenes, ranging from TV-material to home-made super-8 movies. The common factor is death by some means.", box_art: "https://www.allhorror.com/public/uploads/2021/10/fhHzqDrdHLqjawXLXoV3w4FDOUd.jpg", sub_genre: "Documentary Horror", year: 1978),
Movie.create!(name: "My Amityville Horror", description: "For the first time in 35 years, Daniel Lutz recounts his version of the infamous Amityville haunting that terrified his family in 1975. ", box_art: "https://www.allhorror.com/public/uploads/2020/09/sh7Hbs4PWFFTYOlMLXW3JZt0veK.jpg", sub_genre: "Documentary Horror", year: 2012),
Movie.create!(name: "Room 237", description: "A subjective documentary that explores various theories about hidden meanings in Stanley Kubrick's classic film The Shining. Five very different points of view are illuminated through voice over, film clips, animation and dramatic reenactments.", box_art: "https://www.allhorror.com/public/uploads/2018/06/7qu60yUk1GlJY0cG6fScOVPsxyN.jpg", sub_genre: "Documentary Horror", year: 2012),
Movie.create!(name: "Cropsey", description: "Realizing the urban legend of their youth has actually come true; two filmmakers delve into the mystery surrounding five missing children and the real-life boogeyman linked to their disappearances.", box_art: "https://www.allhorror.com/public/uploads/2018/03/rDQWbOOA3OLmkTq89hW1ilGEvHG.jpg", sub_genre: "Documentary Horror", year: 2010),
Movie.create!(name: "Never Sleep Again: The Elm Street Legacy", description: "For decades, Freddy Krueger has slashed his way through the dreams of countless youngsters, scaring up over half a billion dollars at the box office across eight terrifying, spectacular films.", box_art: "https://www.allhorror.com/public/uploads/2018/04/5xh0YgfNaSy711qwngOTJk0i3id.jpg", sub_genre: "Documentary Horror", year: 2010),
Movie.create!(name: "Smoke And Mirrors: The Story Of Tom Savini", description: "Tom Savini is one of the greatest special effects legends in the history of cinema, but little is known about his personal life until now. For the first time ever a feature length film has covered not only Tom's amazing career spanning over four decades, but his personal life as well.", box_art: "https://www.allhorror.com/public/uploads/2020/01/zuVcwjT6P1J15NSgBtswpVBvSrWzuVcwjT6P1J15NSgBtswpVBvSrW-1.jpg", sub_genre: "Documentary Horror", year: 2015),
Movie.create!(name: "The Nightmare", description: "Eight people experience sleep paralysis, a condition which leaves them unable to move, speak or react.", box_art: "https://www.allhorror.com/public/uploads/2018/03/cJdvEQSw9ICjohj28YOsHcgq3Po.jpg", sub_genre: "Documentary Horror", year: 2015),
Movie.create!(name: "The Jeffrey Dahmer Files", description: "An experimental documentary film that uses archival footage, interviews, and fictionalized scenarios to tell the story of the people around Jeffrey Dahmer during the summer of his arrest in 1991.", box_art: "https://www.allhorror.com/public/uploads/2018/06/eIIPonlNZAhAAmcoa1deoHpIFJ7.jpg", sub_genre: "Documentary Horror", year: 2013),
Movie.create!(name: "Scary Stories", description: "A documentary about children's horror classic Scary Stories to Tell in the Dark. It includes the author's family, scholars, folklorists, artists, and children's book authors such as R.L. Stine, Q.L. Pearce, and more.", box_art: "https://www.allhorror.com/public/uploads/2020/09/Scary%20Stories%20(2019)%20Poster.jpg", sub_genre: "Documentary Horror", year: 2019),
Movie.create!(name: "To Hell And Back: The Kane Hodder Story", description: "To Hell and Back: The Kane Hodder Story is the harrowing story of a stuntman overcoming a dehumanizing childhood filled with torment and bullying in Sparks, Nevada. After surviving a near-death burn accident, he worked his way up through Hollywood, leading to his ultimate rise as Jason Voorhees in the Friday the 13th series and making countless moviegoers forever terrified of hockey masks and summer camp", box_art: "https://www.allhorror.com/public/uploads/2018/05/wxZtvvQ45mmppJKw7zCnL0viQEE.jpg", sub_genre: "Documentary Horror", year: 2017),
Movie.create!(name: "Dinner With Leatherface", description: "A look at poet, author, filmmaker, actor and horror icon, Gunnar Hansen, the original Leatherface in the first Texas Chainsaw Massacre, from friends, colleagues, filmmakers, actors and anyone who knew one of the nicest people affiliated with the horror genre.", box_art: "https://www.allhorror.com/public/uploads/2020/09/okgrTxL6TLsC5rpzRD7S5MQCGgx.jpg", sub_genre: "Documentary Horror", year: 2020),

### PSYCHOLOGICAL HARD CODE DATA

Movie.create!(name: "Donnie Darko", description: "After narrowly escaping a bizarre accident, a troubled teenager is plagued by visions of a large bunny rabbit that manipulates him to commit a series of crimes.", box_art: "https://www.allhorror.com/public/uploads/2018/05/nmb4QhCRmdfNP6rgb81yUFgI83l.jpg", sub_genre: "Psychological Horror", year: 2001),
Movie.create!(name: "Se7en", description: "Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer's mind, while his novice partner, Mills, scoffs at his efforts to unravel the case", box_art: "https://www.allhorror.com/public/uploads/2018/04/8zw8IL4zEPjkh8Aysdcd0FwGMb0.jpg", sub_genre: "Psychological Horror", year: 1995),
Movie.create!(name: "Hard Candy", description: "A mature 14-year old girl meets a charming 32-year old photographer on the Internet. Suspecting that he is a pedophile, she goes to his home in an attempt to expose him.", box_art: "https://www.allhorror.com/public/uploads/2018/05/1xInhmQVOOVS7xFT5DthpIwUTDI.jpg", sub_genre: "Psychological Horror", year: 2005),
Movie.create!(name: "Red State", description: "Set in Middle America, a group of teens receive an online invitation for sex, though they soon encounter Christian fundamentalists with a much more sinister agenda.", box_art: "https://www.allhorror.com/public/uploads/2018/03/h43jPTebYOabSXqNQqrRQpg6DPc.jpg", sub_genre: "Psychological Horror", year: 2011),
Movie.create!(name: "Split", description: "Though Kevin has evidenced 23 personalities to his trusted psychiatrist, Dr. Fletcher, there remains one still submerged who is set to materialize and dominate all the others. Compelled to abduct three teenage girls led by the willful, observant Casey, Kevin reaches a war for survival among all of those contained within him — as well as everyone around him — as the walls between his compartments shatter apart.", box_art: "https://www.allhorror.com/public/uploads/2018/03/rXMWOZiCt6eMX22jWuTOSdQ98bY.jpg", sub_genre: "Psychological Horror", year: 2017),
Movie.create!(name: "Midsommar", description: "A young couple travels to Sweden to visit their friend’s rural hometown and attend its mid-summer festival. What begins as an idyllic retreat quickly descends into an increasingly violent and bizarre competition at the hands of a pagan cult.", box_art: "https://www.allhorror.com/public/uploads/2021/10/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg", sub_genre: "Psychological Horror", year: 2019),
Movie.create!(name: "Hereditary", description: "After their reclusive grandmother passes away, the Graham family tries to escape the dark fate they've inherited.", box_art: "https://www.allhorror.com/public/uploads/2018/05/wihYuMsQADWrSaVThaJunM2wR4V.jpg", sub_genre: "Psychological Horror", year: 2018),
Movie.create!(name: "The Shining", description: "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter. But they aren't prepared for the madness that lurks within.", box_art: "https://www.allhorror.com/public/uploads/2021/10/b6ko0IKC8MdYBBPkkA1aBPLe2yz.jpg", sub_genre: "Psychological Horror", year: 1980),
Movie.create!(name: "Psycho", description: "When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother. The place seems quirky, but fine… until Marion decides to take a shower.", box_art: "https://www.allhorror.com/public/uploads/2021/10/nXjkXxpsE7ZGRCVd6PKkrf9tgsL.jpg", sub_genre: "Psychological Horror", year: 1960),
Movie.create!(name: "The Brain That Wouldn't Die", description: "Dr. Bill Cortner and his fiancée, Jan Compton, are driving to his lab when they get into a horrible car accident. Compton is decapitated. But Cortner is not fazed by this seemingly insurmountable hurdle. His expertise is in transplants, and he is excited to perform the first head transplant. Keeping Compton's head alive in his lab, Cortner plans the groundbreaking yet unorthodox surgery. First, however, he needs a body.", box_art: "https://www.allhorror.com/public/uploads/2018/08/lEmcF0P87S1sGKKkzZwIYYbqv6RlEmcF0P87S1sGKKkzZwIYYbqv6R-1.jpg", sub_genre: "Psychological Horror", year: 1962),

### FOUND FOOTAGE HARD CODE DATA

Movie.create!(name: "Cannibal Holocaust", description: "A New York University professor returns from a rescue mission to the Amazon rainforest with the footage shot by a lost team of documentarians who were making a film about the area's local cannibal tribes.", box_art: "https://www.allhorror.com/public/uploads/2021/10/q8TR9TEePfYCFNvOo85Pwcd5pO5.jpg", sub_genre: "Found Footage", year: 1980),
Movie.create!(name: "The McPherson Tape", description: "On October 8th, 1983, the McPherson family gathered together to celebrate the 5th birthday of Michelle, the littlest member of their household. Everything was captured on VHS by Michael McPherson and his new camcorder — including the alien invasion.", box_art: "https://www.allhorror.com/public/uploads/2021/10/g65RZ82jaxwDkVWBK1Dfs90rE80g65RZ82jaxwDkVWBK1Dfs90rE80-1.jpg", sub_genre: "Found Footage", year: 1989),
Movie.create!(name: "The Blair Witch Project", description: "In October of 1994 three student filmmakers disappeared in the woods near Burkittsville, Maryland, while shooting a documentary. A year later their footage was found.", box_art: "https://www.allhorror.com/public/uploads/2021/10/9050VGrYjYrEjpOvDZVAngLbg1f.jpg", sub_genre: "Found Footage", year: 1999),
Movie.create!(name: "Paranormal Activity", description: "After a young, middle class couple moves into a suburban 'starter' tract house, they become increasingly disturbed by a presence that may or may not be somehow demonic but is certainly most active in the middle of the night. Especially when they sleep. Or try to.", box_art: "https://www.allhorror.com/public/uploads/2021/10/1bjA7de4O0NhMsaOqwvrecophUs.jpg", sub_genre: "Found Footage", year: 2007),
Movie.create!(name: "Troll Hunter", description: "A group of students investigates a series of mysterious bear killings, but learns that there are much more dangerous things going on. They start to follow a mysterious hunter, learning that he is actually a troll hunter.", box_art: "https://www.allhorror.com/public/uploads/2018/03/hee6nsDsmemyxpO26TZ7wiODnDO.jpg", sub_genre: "Found Footage", year: 2010),
Movie.create!(name: "The Conspiracy", description: "A documentary about conspiracy theories takes a horrific turn after the filmmakers uncover an ancient and dangerous secret society.", box_art: "https://www.allhorror.com/public/uploads/2018/05/nOnN9nlaVTKQ5QsaeaTNF4nE7Ot.jpg.", sub_genre: "Found Footage", year: 2012),
Movie.create!(name: "The Taking Of Deborah Logan", description: "What starts as a poignant medical documentary about Deborah Logan's descent into Alzheimer's disease and her daughter's struggles as caregiver degenerates into a maddening portrayal of dementia at its most frightening, as hair-raising events begin to plague the family and crew and an unspeakable malevolence threatens to tear the very fabric of sanity from them all.", box_art: "https://www.allhorror.com/public/uploads/2018/03/lVHsBxkEXSH25TaUfyYF4KfrhlB.jpg", sub_genre: "Found Footage", year: 2014),
Movie.create!(name: "As Above, So Below", description: "When a team of explorers ventures into the catacombs that lie beneath the streets of Paris, they uncover the dark secret that lies within this city of the dead.", box_art: "https://www.allhorror.com/public/uploads/2018/03/rXhroOVTfR4Dde7Vci2L3FVGAZh.jpg", sub_genre: "Found Footage", year: 2014),
Movie.create!(name: "The Vatican Tapes", description: "In a highly secured vault deep within the walls of Vatican City, the Catholic Church holds thousands of old films and video footage documenting exorcisms/supposed exorcisms and other unexplained religious phenomena they feel the world is not ready to see. This is the first tape - Case 83-G - stolen from these archives and exposed to the public by an anonymous source.", box_art: "https://www.allhorror.com/public/uploads/2018/03/uiKoHzltaCzHOzvef9tU4HKhqsc.jpg", sub_genre: "Found Footage", year: 2015),
Movie.create!(name: "Headgame", description: "A group of young people awake, locked inside a warehouse with cameras screwed into their heads. It becomes apparent that they are unwilling competitors in a deadly game, and they will need to murder each other if they hope to survive.", box_art: "https://www.allhorror.com/public/uploads/2018/05/fDFVANRnIcBNvokOMZlfhCFjWl.jpg", sub_genre: "Found Footage", year: 2018),

### GORE HARD CODE DATA

Movie.create!(name: "Blood Feast", description: "In the sleepy suburbs of Miami, seemingly normal Egyptian immigrant Fuad Ramses (Mal Arnold) runs a successful catering business. He also murders young women and plans to use their body parts to revive the goddess Ishtar. The insane Ramses hypnotizes a socialite in order to land a job catering a party for her debutante daughter, Suzette Fremont (Connie Mason), and turns the event into an evening of gruesome deaths, bloody dismemberment and ritual sacrifice.", box_art: "https://www.allhorror.com/public/uploads/2021/10/u6mWxgOrNAF3AaevaGEE4NqCwcQ.jpg", sub_genre: "Gore Horror", year: 1963),
Movie.create!(name: "The Hills Have Eyes", description: "On the way to California, a family has the misfortune to have their car break down in an area closed to the public, and inhabited by violent savages ready to attack.", box_art: "https://www.allhorror.com/public/uploads/2021/10/vPsFU9p1BYZXVZbSYqM2KtE5U0E.jpg", sub_genre: "Gore Horror", year: 1977),
Movie.create!(name: "Event Horizon", description: "In the year 2047 a group of astronauts are sent to investigate and salvage the long lost starship "Event Horizon". The ship disappeared mysteriously 7 years before on its maiden voyage and with its return comes even more mystery as the crew of the "Lewis and Clark" discover the real truth behind its disappearance and something even more terrifying.", box_art: "https://www.allhorror.com/public/uploads/2021/10/qfluaDXv0cIdLwgQWzNB2piHL2q.jpg", sub_genre: "Gore Horror", year: 1997),
Movie.create!(name: "From Dusk Till Dawn", description: "Seth Gecko and his younger brother Richard are on the run after a bloody bank robbery in Texas. They escape across the border into Mexico and will be home-free the next morning, when they pay off the local kingpin. They just have to survive 'from dusk till dawn' at the rendezvous point, which turns out to be a Hell of a strip joint.", box_art: "https://www.allhorror.com/public/uploads/2021/10/kwhlLAlxIHLSbwOukBQkDJK7NGA.jpg", sub_genre: "Gore Horror", year: 1996),
Movie.create!(name: "House Of 1000 Corpses", description: "Two teenage couples traveling across the backwoods of Texas searching for urban legends of serial killers end up as prisoners of a bizarre and sadistic backwater family of serial killers.", box_art: "https://www.allhorror.com/public/uploads/2021/10/zEAVm1zpjkk4XFL2i5EZehkEgkH.jpg", sub_genre: "Gore Horror", year: 2003),
Movie.create!(name: "Hostel", description: "Three backpackers head to a Slovakian city that promises to meet their hedonistic expectations, with no idea of the hell that awaits them.", box_art: "https://www.allhorror.com/public/uploads/2021/10/1etNL6wz2BRRSUAyYmKnDwiQOgg.jpg", sub_genre: "Gore Horror", year: 2005),
Movie.create!(name: "The Collector", description: "Desperate to repay his debt to his ex-wife, an ex-con plots a heist at his new employer's country home, unaware that a second criminal has also targeted the property, and rigged it with a series of deadly traps.", box_art: "https://www.allhorror.com/public/uploads/2021/10/e33HSokiAxhj8ptpAr2xAU4jnd8.jpg", sub_genre: "Gore Horror", year: 2009),
Movie.create!(name: "The Human Centipede (First Sequence)", description: "During a stopover in Germany in the middle of a carefree road trip through Europe, two American girls find themselves alone at night when their car breaks down in the woods. Searching for help at a nearby villa, they are wooed into the clutches of a deranged retired surgeon who explains his mad scientific vision to his captives' utter horror. They are to be the subjects of his sick lifetime fantasy: to be the first to connect people, one to the next, and in doing so bring to life "the human centipede."", box_art: "https://www.allhorror.com/public/uploads/2018/03/rhy5WMyLVmYQ9PfEM60pg25E3TL.jpg", sub_genre: "Gore Horror", year: 2009),
Movie.create!(name: "A Serbian Film", description: "Milos, a retired porn star, leads a normal family life trying to make ends meet. Presented with the opportunity of a lifetime to financially support his family for the rest of their lives, Milos must participate in one last mysterious film. From then on, Milos is drawn into a maelstrom of unbelievable cruelty and mayhem.", box_art: "https://www.allhorror.com/public/uploads/2018/03/edM906NOM5WxaaAMeTsgDeqnBDr.jpg", sub_genre: "Gore Horror", year: 2010),
Movie.create!(name: "Saw", description: "Obsessed with teaching his victims the value of life, a deranged, sadistic serial killer abducts the morally wayward. Once captured, they must face impossible choices in a horrific game of survival. The victims must fight to win their lives back, or die trying...", box_art: "https://www.allhorror.com/public/uploads/2021/10/pparEGTCxcTiImyVFoKD0LX11N8.jpg", sub_genre: "Gore Horror", year: 2004),

### HAUNTED HOUSE HARD CODE DATA

Movie.create!(name: "House Of The Damned", description: "An architect and his wife are staying in an empty castle in California. They are joined by an unhappily married lawyer and his wife. Things start getting strange when they spot a half man/half beast prowling around the house and keep seeing a headless woman wandering the grounds.", box_art: "https://www.allhorror.com/public/uploads/2021/10/h1u9MEbEqOFVh3yBlcvcm1eqX1f.jpg", sub_genre: "Haunted House", year: 1963),
Movie.create!(name: "The Amityville Horror", description: "George Lutz and his wife Kathleen, move into their Long Island dream house with their children only for their lives to be turned into a hellish nightmare. The legacy of a murder committed in the house gradually affects the family and a priest is brought in to try and exorcise the demonic presence from their home.", box_art: "https://www.allhorror.com/public/uploads/2021/10/s8FRFIiwJpSZILl3qMtI79TFBip.jpg", sub_genre: "Haunted House", year: 1979),
Movie.create!(name: "Beetlejuice", description: "Thanks to an untimely demise via drowning, a young couple end up as poltergeists in their New England farmhouse, where they fail to meet the challenge of scaring away the insufferable new owners, who want to make drastic changes. In desperation, the undead newlyweds turn to an expert frightmeister, but he's got a diabolical agenda of his own.", box_art: "https://www.allhorror.com/public/uploads/2018/10/gWnW7vxm8yr01TVLQhL4aI02orp.jpg", sub_genre: "Haunted House", year: 1988),
Movie.create!(name: "Waxwork", description: "Wealthy slacker college student Mark, his new girlfriend Sarah, and their friends are invited to a special showing at a mysterious wax museum which displays 18 of the most evil men of all time. After his ex-girlfriend and another friend disappear, Mark becomes suspicous. What he doesn't know is that they have been made a part of the exhibit, by first living out the scene and then being murdered in", box_art: "https://www.allhorror.com/public/uploads/2021/10/ohFgl7yIrnaqptUdsXDXLKPdHGt.jpg", sub_genre: "Haunted House", year: 1988),
Movie.create!(name: "Ju-On: The Grudge", description: "A mysterious and vengeful spirit marks and pursues anybody who dares enter the house in which it resides.", box_art: "https://www.allhorror.com/public/uploads/2021/10/6q1hlBC6rudc3mHwXsbMBR2xAT6.jpg", sub_genre: "Haunted House", year: 2002),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),
Movie.create!(name:, description:, box_art:, sub_genre:, year:),