# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

### ACTION HORROR HARD CODE DATA

Movie.create!(name: "Attack Of The Killer Hog", description: "The new drug Kimanga is everywhere in the city. And the apocalypse is near. The first sign is a plush pig. But two guys are going to clear the city out and stop the apocalypse.", box_art: "https://www.themoviedb.org/t/p/w500/f9c51qg1oqxazgTAXnsZnklI5QI.jpg", sub_genre: "Action", year: 2003),
Movie.create!(name: "Demon Hunter", description: "Cosette is cursed. Demons Ghouls and Ghosts from the darkest corners of Hell are summoned to bring her to the other side. Now Cosette and Klaus her protector must face an unspeakable evil in an attempt to free her from this demonic curse.", box_art: "https://www.themoviedb.org/t/p/w500/zO98iiymllC5L995Izo5vGjeppx.jpg", sub_genre: "Action" year: 2012),
Movie.create!(name: "Jurassic Shark", description: "When an oil company unwittingly unleashes a prehistoric shark from its icy prison, the Jurassic killer maroons a group of art thieves and a group of college students on an abandoned island", box_art: "https://www.allhorror.com/public/uploads/2021/10/8yJVr0cH9w7f5pw5mjmtHMNcpr88yJVr0cH9w7f5pw5mjmtHMNcpr8-1.jpg", sub_genre: "Action" year: 2012),
Movie.create!(name: "122", description: "During a bloody night, a young man and his lover are struggling, not to get to the hospital, but to escape and survive.", box_art: "https://m.media-amazon.com/images/M/MV5BZTBiYzZhMWUtNzgzNS00ZjkzLTgxZjQtMGZmYjNhYzE1ODdlXkEyXkFqcGdeQXVyNDQ3Njc5MzM@._V1_.jpg", sub_genre: "Action", year: 2019),
Movie.create!(name: "Sky Sharks", description: "A team of Arctic geologists stumble across an abandoned laboratory in which the Nazis developed an incredible and brutal secret weapon during the final months of WW2. Deep in the ice, they accidentally awake a deadly army of flying zombie sharks ridden by genetically mutated, undead super-humans, who are unleashed into the skies, wreaking their bloodthirsty revenge on any aircraft that takes to the air.", box_art: "https://www.allhorror.com/public/uploads/2019/03/y4cxche6larlzuEsV9iwCYBubm2.jpg", sub_genre: "Action", year: 2020),
Movie.create!(name: "Originless", description: "A former drug runner battles supernatural assassins after taking a sick girl under his protection.", box_art: "https://www.allhorror.com/public/uploads/2021/10/77lI0btz8qkExY13MKXaPrf4cA677lI0btz8qkExY13MKXaPrf4cA6-1.jpg", sub_genre: "Action", year: 2020),
Movie.create!(name: "Amityville Uprising", description: "A chemical blast at a military base sets off a supernatural disaster. As Sgt. Dash tries to keep the peace at the local police station, the explosion unleashes a toxic acid rain that dissolves the flesh of anyone trapped in it. Even worse, it causes the dead to rise again and attack the living. Can Dash and fellow officer Nina Rossi figure out who is friend and foe, fend off the attacks, and defend their colleagues until the savage cataclysm subsides?", box_art: "https://www.allhorror.com/public/uploads/2021/11/RrzMH1EOUeuAogTZr1JPHsTAAg.jpg", sub_genre: "Action", year: 2022),
Movie.create!(name: "The Cursed: Dead Man’s Prey", description: "It tells the story of a girl, who pursues the truth of an incident in which the culprit of a peculiar serial murder case turns out to be a revived corpse, but who is manipulating the dead?", box_art: "https://www.allhorror.com/public/uploads/2021/07/jWe9dx74uVltztprS4SpKJRTaCY.jpg", sub_genre: "Action", year: 2021),
Movie.create!(name: "Blood Red Sky", description: "A woman with a mysterious illness is forced into action when a group of terrorists attempt to hijack a transatlantic overnight flight. In order to protect her son she will have to reveal a dark secret, and unleash the inner monster she has fought to hide.", box_art: "https://www.allhorror.com/public/uploads/2021/10/ky8Fua6PD7FyyOA7JACh3GDETli.jpg", sub_genre: "Action", year: 2021)
Movie.create!(name: "Stellanomicon: Future Fear", description: "In a distant future, an archeologist must use ancient technology in hopes of finding a way to fight back an army of alien attackers and escape the planet.", box_art: "https://www.allhorror.com/public/uploads/2021/10/xBJlIZFYumZRBL5fF8GLl4TBT2G.jpg", sub_genre: "Action", year: 2021),
Movie.create!(name: "Ebola Rex", description: "An infected T-Rex escapes from a Science Lab in downtown Los Angeles, destroying everything in it's path.", box_art: "https://www.allhorror.com/public/uploads/2021/03/yXKNAuL3SRog5hB3l3ykVOZqhhC.jpg", sub_genre: "Action", year: 2021),

### ALIENS HORROR HARD CODE DATA

Movie.create!(name: "Village Of The Damned", description: "In a small English village everyone suddenly falls unconscious. When they awake every woman of child bearing age is pregnant. The resulting children have the same strange blond hair, eyes and a strong connection to each other.", box_art: "https://www.allhorror.com/public/uploads/2021/10/qcpXud1UjQzlSe9A062w8Wqgira.jpg", sub_genre: "Alien", year: 1960),
Movie.create!(name: "The Crawling Eye", description: "Alien creatures invade a remote mountain resort in Switzerland.", box_art: "https://www.allhorror.com/public/uploads/2021/10/onncV1X9RRk7vs9vJ0mpCeFIrzQ.jpg", sub_genre: "Alien", year: 1958),
Movie.create!(name: "Alien", description: "During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.", box_art: "https://www.allhorror.com/public/uploads/2021/10/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg", sub_genre: "Alien", year: 1979),
Movie.create!(name: "Phantasm", description: "A young boy and his friends face off against a mysterious grave robber known only as the Tall Man, who keeps a mysterious arsenal of terrible weapons with him.", box_art: "https://www.allhorror.com/public/uploads/2021/10/eR0uJ0Wje1lYJ4aHEpkcjgIM8d7.jpg", sub_genre: "Alien", year: 1979),
Movie.create!(name: "The Thing", description: "Scientists in the Antarctic are confronted by a shape-shifting alien that assumes the appearance of the people it kills.", box_art: "https://www.allhorror.com/public/uploads/2021/10/tzGY49kseSE9QAKk47uuDGwnSCu.jpg", sub_genre: "Alien", year: 1982),
Movie.create!(name: "They Live", description: "Nada, a down-on-his-luck construction worker, discovers a pair of special sunglasses. Wearing them, he is able to see the world as it really is: people being bombarded by media and government with messages like "Stay Asleep", "No Imagination", "Submit to Authority". Even scarier is that he is able to see that some usually normal-looking people are in fact ugly aliens in charge of the massive campaign to keep humans subdued.", box_art: "https://www.allhorror.com/public/uploads/2021/10/ngnybFTuopfbfmmEeX9jjBQQmF6.jpg", sub_genre: "Alien", year: 1988),
Movie.create!(name: "Dreamcatcher", description: "Four boyhood pals perform a heroic act and are changed by the powers they gain in return. Years later, on a hunting trip in the Maine woods, they're overtaken by a vicious blizzard that harbors an ominous presence. Challenged to stop an alien force, the friends must first prevent the slaughter of innocent civilians by a military vigilante ... and then overcome a threat to the bond that unites the four of them.", box_art: "https://www.allhorror.com/public/uploads/2021/10/vEA305YK7QCjK02NP5OFqYsDEVQ.jpg", sub_genre: "Alien", year: 2003),
Movie.create!(name: "Rakka", description: "A tale of a dystopian future where an unknown alien group have colonised the earth and humans struggle to fight back.", box_art: "https://www.allhorror.com/public/uploads/2021/10/4wVeP9BHsQul7CRgdrfiUt1Rds14wVeP9BHsQul7CRgdrfiUt1Rds1-1.jpg", sub_genre: "Alien", year: 2017),
Movie.create!(name: "Psycho Goreman", description: "Siblings Mimi and Luke unwittingly resurrect an ancient alien overlord. Using a magical amulet, they force the monster to obey their childish whims, and accidentally attract a rogues’ gallery of intergalactic assassins to small-town suburbia.", box_art: "https://www.allhorror.com/public/uploads/2021/10/foQnDv051kQ7satMQkbkPsUxzkDfoQnDv051kQ7satMQkbkPsUxzkD-1.jpg", sub_genre: "Alien", year: 2021),
Movie.create!(name: "Invaders From Mars", description: "In the early hours of the night, young David Maclean sees a flying saucer land and disappear into the sand dunes just beyond his house. Slowly, all of the adults, including his once loving parents, begin to act strangely.", box_art: "https://www.allhorror.com/public/uploads/2021/10/pVR2c0bigL5w1K29H99svqHj2YHpVR2c0bigL5w1K29H99svqHj2YH-1.jpg", sub_genre: "Alien", year: 1953),

### ANTHOLOGY HARD CODE DATA

Movie.create!(name: "Dr. Terror's House Of Horrors", description: "A man of mystery known only as Doctor Terror recounts seven stories from his casebook of personal encounters with evil and the supernatural.", box_art: "https://www.allhorror.com/public/uploads/2018/10/iNJSXyRPbke0daGrXU8FGZLbpbdiNJSXyRPbke0daGrXU8FGZLbpbd-1.jpg", sub_genre: "Anthology", year: 1943),
Movie.create!(name: "Trilogy Of Terror", description: "Three bizarre horror stories ending with the story of an African doll out for blood.", box_art: "https://www.allhorror.com/public/uploads/2021/10/2t2TJz5cIVQuzQsQWFZFNYfuFnm.jpg", sub_genre: "Anthology", year: 1975),
Movie.create!(name: "Creepshow", description: "Inspired by the E.C. comics of the 1950s, George A. Romero and Stephen King bring five tales of terror to the screen.", box_art: "https://www.allhorror.com/public/uploads/2021/10/4SoyTCEpsgLjX6yAyMsx3AsAyRQ.jpg", sub_genre: "Anthology", year: 1982),
Movie.create!(name: "Cradle Of Fear", description: "A gruesome homage to the cult Amicus anthology Asylum, Cradle of Fear unfolds four screamplays all linked by the unspeakable need of an incarcerated child killer to wreak vengeance on those responsible for his imprisonment.", box_art: "https://www.allhorror.com/public/uploads/2021/10/qYNYAFCBd83fOAWIIiL4nG6L2zq.jpg", sub_genre: "Anthology", year: 2001),
Movie.create!(name: "V/H/S", description: "When a group of misfits is hired by an unknown third party to burglarize a desolate house and acquire a rare VHS tape, they discover more found footage than they bargained for.", box_art: "https://www.allhorror.com/public/uploads/2018/03/yo49x6Jhr1ecCjy1ByFqwAbtARJ.jpg", sub_genre: "Anthology", year: 2012),
Movie.create!(name: "All Hallows' Eve", description: "While watching two children on Halloween night, a babysitter finds an old VHS tape in the kids' trick or treat bag. The tape features three tales of terror, all linked together by a murderous clown. As the night goes on strange things begin to occur in the house. It isn't long before the babysitter learns the horrifying truth... the maniacal clown is slowly working his way into her reality.", box_art: "https://www.allhorror.com/public/uploads/2018/03/uh2DbCCj83krRPl3X2wYMQQLasZuh2DbCCj83krRPl3X2wYMQQLasZ-1.jpg", sub_genre: "Anthology", year: 2013),
Movie.create!(name: "The ABCs Of Death", description: "An ambitious anthology film featuring segments directed by over two dozen of the world's leading talents in contemporary genre film. Inspired by children's educational ABC books, the motion picture is comprised of 26 individual chapters, each helmed by a different director assigned a letter of the alphabet", box_art: "https://www.allhorror.com/public/uploads/2018/03/9rAaRHk7GkYCxjOlBnJLC0kXrSy.jpg",  sub_genre: "Anthology", year: 2013),
Movie.create!(name: "Killroy Was Here", description: "A horror anthology centred around the phenomenon of the "Kilroy Was Here" graffiti.",box_art: "https://www.allhorror.com/public/uploads/2020/08/kZNop4kIfPmghbPrvLNPTPyz6tw.jpg",sub_genre: "Anthology",year: 2020),
Movie.create!(name: "The Haunted Hotel", description: "A compendium of eight ghost stories, all set within an abandoned hotel in Suffolk.", box_art: "https://www.allhorror.com/public/uploads/2021/10/rtQnew9MbwUb1hmF2E65j5LJdkLrtQnew9MbwUb1hmF2E65j5LJdkL-1.jpg", sub_genre: "Anthology", year: 2021),
Movie.create!(name: "Tales From The Hood", description: "A strange funeral director tells four strange tales of horror with an African American focus to three drug dealers he traps in his place of business.", box_art: "https://www.allhorror.com/public/uploads/2021/10/rmlDLtt03igCdlW7UOF2AXCsy4d.jpg",
sub_genre: "Anthology", year: 1995),

### BLACK HORROR HARD CODE DATA

Movie.create!(name: "Blacula", description: "An 18th century African prince is turned into a vampire while visiting Transylvania. Two centuries later, he rises from his coffin attacking various residents of Los Angeles and meets Tina, a woman who he believes is the reincarnation of his deceased wife.",box_art: "https://www.allhorror.com/public/uploads/2021/10/yLqtFeZfRPoUUzzro3ogCdobB6q.jpg", sub_genre: "Black", year: 1972),
Movie.create!(name: "Scream Blacula Scream", description: "After a dying Voodoo queen chooses an adopted apprentice as her successor, her true heir is outraged. Seeking revenge, he buys the bones of Blacula the vampire off of a dealer, and uses voodoo to bring the vampire back to do his bidding.", box_art: "https://www.allhorror.com/public/uploads/2021/10/fNj2dm4YTboK73uNcctP9ABzl6i.jpg", sub_genre: "Black", year: 1973),
Movie.create!(name: "Bones", description: "Over 20 years after his death by a gunshot, Jimmy Bones comes back as a ghost to wreak revenge on those who killed him and to clean up his neighborhood.", box_art: "https://www.allhorror.com/public/uploads/2021/10/7UOHEPTQMaiwaI14CGxd5yFAPMZ.jpg", sub_genre: "Black", year: 2001),
Movie.create!(name: "Shadow: Dead Riot", description: "Evil voodoo-practicing serial killer Shadow gets executed for murdering pregnant women. Twenty years later the prison Shadow was put to death at has been turned into an experimental women's penitentiary. Tough and fiercely autonomous new inmate Solitaire has some kind of link with Shadow. When Shadow and his lethal shambling zombie minions are resurrected, it's up to Solitaire to stop them.", box_art: "https://www.allhorror.com/public/uploads/2021/10/labFmu8KL7DGIOp9w5n5PNQALtl.jpg", sub_genre: "Black", year: 2006),
Movie.create!(name: "Nailed", description: "A pair of crooks on the run from the law gets more than they bargained for when they break into a seemingly abandoned house looking for a place to hole up and find that it's controlled by an evil spirit that will do anything to protect its sole, sickly resident. Suddenly, jail's not looking so bad.", box_art: "https://www.allhorror.com/public/uploads/2018/03/rb8pbhDwZU1EFmS3SdrNHlllBR4-238x347.jpg", sub_genre: "Black", year: 2006),
Movie.create!(name: "Killjoy", description: "Deep in an inner city hell, a ghastly figure is killing off the bad guys. A vigilante, or a demon? For the beautiful high school student, Jada, that's the question that will bring her face to face with the killer clown Killjoy.", box_art: "https://www.allhorror.com/public/uploads/2018/03/7mqFe0lNXRuzTqLO2pxoj9H6stU-230x357.jpg", sub_genre: "Black", year: 2000),
Movie.create!(name: "Vampire In Brooklyn", description: "Maximillian, the lone survivor of a race of vampires, comes to Brooklyn in search of a way to live past the next full moon. His ticket to survival is Rita, a NYPD detective who doesn't know she's half vampire -- and Maximillian will do whatever's necessary to put her under his spell.", box_art: "https://www.allhorror.com/public/uploads/2021/10/i8ZD5LsBjwF45MsZ1nCClpvaOcn.jpg", sub_genre: "Black", year: 1995),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),
Movie.create!(name:,description:,box_art:,sub_genre:,year:),